# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-07 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cuentas_montadas',
            field=models.BooleanField(default=False),
        ),
    ]
